# SPDX-FileCopyrightText: 2025 multi_bimap contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "multi_bimap"
version = "0.2.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Many-to-many bidirectional map in Rust."
repository = "https://github.com/mikwielgus/multi_bimap"
documentation = "https://docs.rs/multi_bimap"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["bidirectional", "bijection", "container", "two-way", "map"]
categories = ["algorithms", "data-structures", "no-std"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
## Enables `undoredo` support.
undoredo = ["dep:undoredo"]

[dependencies]
maplike = "0.13.0"
undoredo = { version = "0.13", features = ["derive"], optional = true }

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
