[package]
name = "multi_bimap"
version = "0.1.0"
edition = "2024"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Many-to-many bidirectional map in Rust."
documentation = "https://docs.rs/multi_bimap"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["bidirectional", "bijection", "two-way", "map", "container"]

[dependencies]
maplike = "0.13.0"

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
